version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_DB=waypoints
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 5
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=waypoints
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "8001:8001"
    links:
      - db:db
    depends_on:
      - db
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - api
volumes:
  data:
