openapi: 3.0.0
info:
  title: Waypoint API
  description: Waypoint storage goserver
  version: 1.0.0
servers:
  - url: http://localhost/api/v1
    description: Local server url
paths:
  /waypoints:
    get:
      summary: Returns the list of saved waypoints.
      responses:
        '200':
          description: A JSON array of waypoints
          content:
            application/json:
              schema:
                type: array
                maxItems: 20
                x-count: 20
                items:
                  $ref: '#/components/schemas/Waypoint'
  /waypoint:
    post:
      summary: Saves a waypoint.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Waypoint'
      responses:
        '200':
          description: A JSON array of waypoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Waypoint'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    Waypoint:
      type: object
      required:
        - latitude
        - longitude
        - name
      properties:
        latitude:
          type: integer
          x-faker: address.latitude
          example: 52.504680
        longitude:
          type: integer
          x-faker: address.longitude
          example: 13.329780
        name:
          type: string
          x-faker: '{{address.streetAddress}}, {{address.zipCode}} {{address.cityName}}, {{address.country}}'
          example: 'Kurfürstendamm 22, 10719 Berlin, Germany'
