// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// SavedWaypoint defines model for SavedWaypoint.
type SavedWaypoint struct {
	// Embedded struct due to allOf(#/components/schemas/Waypoint)
	Waypoint `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/WaypointOrder)
	WaypointOrder `yaml:",inline"`
}

// Waypoint defines model for Waypoint.
type Waypoint struct {
	Latitude  float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
	Name      string  `json:"name"`
}

// WaypointOrder defines model for WaypointOrder.
type WaypointOrder struct {
	Id    string  `json:"id"`
	Order float32 `json:"order"`
}

// CreateJSONBody defines parameters for Create.
type CreateJSONBody Waypoint

// UpdateOrderJSONBody defines parameters for UpdateOrder.
type UpdateOrderJSONBody []WaypointOrder

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody CreateJSONBody

// UpdateOrderJSONRequestBody defines body for UpdateOrder for application/json ContentType.
type UpdateOrderJSONRequestBody UpdateOrderJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Saves a waypoint.
	// (POST /waypoint/{user})
	Create(w http.ResponseWriter, r *http.Request, user string)
	// Returns the list of saved waypoints.
	// (GET /waypoints/{user})
	List(w http.ResponseWriter, r *http.Request, user string)
	// Updates waypoint order.
	// (PUT /waypoints/{user})
	UpdateOrder(w http.ResponseWriter, r *http.Request, user string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// Create operation middleware
func (siw *ServerInterfaceWrapper) Create(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameter("simple", false, "user", chi.URLParam(r, "user"), &user)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter user: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Create(w, r, user)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// List operation middleware
func (siw *ServerInterfaceWrapper) List(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameter("simple", false, "user", chi.URLParam(r, "user"), &user)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter user: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.List(w, r, user)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdateOrder operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrder(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameter("simple", false, "user", chi.URLParam(r, "user"), &user)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter user: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrder(w, r, user)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/waypoint/{user}", wrapper.Create)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/waypoints/{user}", wrapper.List)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/waypoints/{user}", wrapper.UpdateOrder)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWTY8jNRD9K1bBASRvOmE57Po2rDhEWrGID3HYnYO3XUm8tD8oV4cJkf87sjsf3TPZ",
	"IYgBsZfIdvtVvapX/Tp7aIOLwaPnBGoPqd2g03X5LVGgsogUIhJbrMcOU9JrLEveRQQFicn6NeQsjyfh",
	"/QdsGbKEH/UWzS96F4P1XDC6696sQL3dw+eEK1DwWXNm0BzSNydEltddfEMGCfJtljDONqXeabbcm8p9",
	"FchpBgWrLmgGCU7fWdc7UC/nEpz1w+ZZ2R2q8r17jwQS7p6t9K9IoEAbQ5jS7BQ5S+iCX1+RZvFikqdu",
	"r0h0Cp4leO0u6DCG7fdHYGJC5Jthl7MU50d/2PgqGMx5dNZa3n2nHU5vtqH3TLucq9iEv/WW0IB6e27t",
	"uP4Dw9sLczHV7YFS1jxeF2lvgpv1vTUlWjhG+XgDD4jhyRd78a70/h0oMZdlre/K+qXIXz4ozRo4ZnhY",
	"Sbls/SqU5AZTSzayDR7UqUKROJBeo1iHhLSttNhyh+M7N98vQcIWKQ3gxWw+m9fKInodLSh4Xo8kRM2b",
	"2qPm9wO62fcJKdcuhlTnvvRSFyJLAwpeEWrGiiXtkJFSfQNtSVXiHZVSUCLBuH6mHuXBFkpkvNMuVvKM",
	"iZelN/dt4HbAY+JvgtkVUBs84+H9j7GzbeXWfEil2P0o+nWeMFWoMKwHKQafhvn5aj5/srxTC6vJp0r/",
	"tEHR1hYbcdRkVsT7+glZDG58IfvSb3VnjTi0fFbnN/XOadqBqgachB4Rk8B6XQYAjmdwWzCneUqjgVrj",
	"hXl6bRP/t9P0D6S1jC79TY2rTS8H4OLsy5pI76qrVCME9fyCHjeiDV2HbdmKsDo1Pt1X5gfknnwSvEHR",
	"2cTlcio8xpCLYkmI/QVZfo5GMw6O+gm861cJc+/7/qgw/4IvPDnHvxieq2bif+Isw7ilEzNRv5Ef85cC",
	"rZ+/YRynmV6HVndieC566kBC+VWwYY6qabryfBMSqxfz+aLR0TbbRfm392cAAAD//yeAYdK/CgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
