// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// SavedWaypoint defines model for SavedWaypoint.
type SavedWaypoint struct {
	// Embedded struct due to allOf(#/components/schemas/Waypoint)
	Waypoint `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/WaypointOrder)
	WaypointOrder `yaml:",inline"`
}

// Waypoint defines model for Waypoint.
type Waypoint struct {
	Latitude  float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
	Name      string  `json:"name"`
}

// WaypointOrder defines model for WaypointOrder.
type WaypointOrder struct {
	Id    uint64 `json:"id"`
	Order uint8  `json:"order"`
}

// DeleteParams defines parameters for Delete.
type DeleteParams struct {
	Id uint64 `json:"id"`
}

// CreateJSONBody defines parameters for Create.
type CreateJSONBody Waypoint

// UpdateOrderJSONBody defines parameters for UpdateOrder.
type UpdateOrderJSONBody []WaypointOrder

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody CreateJSONBody

// UpdateOrderJSONRequestBody defines body for UpdateOrder for application/json ContentType.
type UpdateOrderJSONRequestBody UpdateOrderJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Deletes a waypoint.
	// (DELETE /api/v1/waypoint/{user})
	Delete(w http.ResponseWriter, r *http.Request, user string, params DeleteParams)
	// Saves a waypoint.
	// (POST /api/v1/waypoint/{user})
	Create(w http.ResponseWriter, r *http.Request, user string)
	// Returns the list of saved waypoints.
	// (GET /api/v1/waypoints/{user})
	List(w http.ResponseWriter, r *http.Request, user string)
	// Updates waypoint order.
	// (PUT /api/v1/waypoints/{user})
	UpdateOrder(w http.ResponseWriter, r *http.Request, user string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// Delete operation middleware
func (siw *ServerInterfaceWrapper) Delete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameter("simple", false, "user", chi.URLParam(r, "user"), &user)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter user: %s", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteParams

	// ------------- Required query parameter "id" -------------
	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		http.Error(w, "Query argument id is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Delete(w, r, user, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Create operation middleware
func (siw *ServerInterfaceWrapper) Create(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameter("simple", false, "user", chi.URLParam(r, "user"), &user)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter user: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Create(w, r, user)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// List operation middleware
func (siw *ServerInterfaceWrapper) List(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameter("simple", false, "user", chi.URLParam(r, "user"), &user)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter user: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.List(w, r, user)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdateOrder operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrder(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "user" -------------
	var user string

	err = runtime.BindStyledParameter("simple", false, "user", chi.URLParam(r, "user"), &user)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter user: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrder(w, r, user)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/waypoint/{user}", wrapper.Delete)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/waypoint/{user}", wrapper.Create)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/waypoints/{user}", wrapper.List)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/waypoints/{user}", wrapper.UpdateOrder)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXS48bNwz+KwLbQwtoPXYTFLu6bdMcDARN0Qd6SPagzNC20tEjEsdZ19B/L6jxYxxP",
	"UrfZBsnF0Ivkp++jyPEWam+Dd+gogdpCqldodRk+jdFHHoToA0YyWJYtpqSXyEPaBAQFiaJxS8hZ7lf8",
	"q9dYE2QJv+o1Nn/oTfDGEdvotn2+APViC19HXICCr6ojgmoXvjpYZHnZweexwQj5LksYRjuF3moy1DUF",
	"+8JHqwkULFqvCSRYfW9sZ0HdTCVY4/rJFc92t3KdfYURJNxfLfSfGEGBbpqIKU0OnrOE1rvlBWFm1ydx",
	"yvSCQAfnWYLTdkSHodl2uzdMFBHptp/lLMVx6y8TnvgGcx6s1YY2P2mLpydr3zmKm5yL2BHfdCZiA+rF",
	"4NLySPMO4d1IXpzqdqaUaQb3GqEjatd4O+l3vtmKl8zkS1BiKnms73l8cyPyt8Vs6a92vjrj6PvHjMDv",
	"I39slPEg12cUmQb2Uc8Z4cPGLTwDajDV0QQy3oE6MCUS+aiXKJY+YVwXqGSoxeGZ25/nIGGNMfXGs8l0",
	"Mi23Deh0MKDgUVmSEDStCteVDqZaz6q3OyfVtksYc4+kRSopxuJoRjRvQMGP/To7idoiYUzlSRuOyY73",
	"0itgXzAkgmKHcldn2DPeaxvKLQgTzZmks7qy8/ymw7g5ui6E/hfHA6nPMyPfsdMUvEt9Ln43nZ6r8tQG",
	"2oj9OfF2hU6krq75lTDfj3uj2jvCXeELoTV14bB6ndjJdgD2QzWuL8QlRU5BzN1at6YRzAEmmpSUS521",
	"Om4OKiWhxV7aCXOglywW7NeAa2bwic5lfhJRf0KZ73p7TPSDbzYPRt+xl5y+SEaYx7V+kLinrW9Evt9W",
	"KOpCcTNQ6DNJHkZ/QepkeVY/0qCALHEkrZ6ZRJ82qT5CYUNo07+UunT5eW84O7Z1HaPelKpT+iioRyOy",
	"3Iraty3WPBV+ceA/vSvQL0hddEnQCkVrEvHhxDiGJu977t2ILL+HRhP2DfkLePIXCfPO5+EHhfkfysOD",
	"Y/yH5LkoJz6TAtOnWzogE+XT6H1lhk3LV0+fjqeRnvlat6LfF11sQQL/KlgRBVVVLe+vfCJ1PZ3O+F/C",
	"3wEAAP//j4hqfPcMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
